### ISSUE TITLE
error: a bin target must be available for `cargo run`

### ISSUE THREAD

**Issue by farmboy0** [ChatImproVR/rust-opengl-openxr-example#1]
I'm trying to run this sample again, it "worked" before at least as far as starting it but now I get this error.
Cargo and Rust 1.64 and 1.65 used currently, not sure which version I originally used.
System: Gentoo Linux

**Comment by Masterchef365** [comment]
Honestly didn't expect anyone to look at this! Updated README with relevant instructions.

**Comment by farmboy0** [comment]
Was using it to test OpenGL+OpenXR with SteamVR, see https://github.com/ValveSoftware/SteamVR-for-Linux/issues/546
